#!/usr/bin/env bash

set -eo pipefail

: "${BASE_URL:=https://api.hitbtc.com}"
: "${PUBLIC_KEY:=$(secret-tool lookup hitbtc_api public_key)}"
: "${SECRET_KEY:=$(secret-tool lookup hitbtc_api secret_key)}"

PROGNAME="$(basename "$0")"

_history_trades() {
	_api_call "/api/3/spot/history/trade" "$@" \
		| jq -r ".[] | [ .timestamp, .symbol, .side, .quantity, .price, .fee ] | @csv" \
		| awk -F, 'BEGIN {OFS = "\t"} { "date \"+%F %T\" --date=" $1 | getline time; $1 = time; print }' \
		| sort -k 1,1 -n
}

_order() {
	_api_call "/api/3/spot/order" "$@" \
		| jq -r '.[] | [ .created_at, .symbol, .side, .quantity, .price, .status ] | @csv' \
		| awk -F, 'BEGIN {OFS = "\t"} { "date \"+%F %T\" --date=" $1 | getline time; $1 = time; print }' \
		| sort -k 1,1 -n
}

_trading_balance() {
	_api_call "/api/3/spot/balance" \
		| jq -r '.[] | [ .currency, .available, .reserved ] |  @csv' \
		| column -s, -t
}

_wallet_balance() {
	_api_call "/api/3/wallet/balance" \
		| jq -r '.[] | [ .currency, .available, .reserved ] |  @csv' \
		| column -s, -t
}

_arg_parser() {
	case "$1" in
	POST|PUT|PATCH|DELETE)
		echo -n "-X $1"
		shift
		;;
	*)
		# Default method
		echo -n "--get"
		;;
	esac
	echo -n " "  # options separator

	while [ -n "$1" ]; do
		case "$1" in
		http*)  echo -n "$1"                ;;
		/api/*) echo -n "$BASE_URL$1"       ;;
		/*)     echo -n "$BASE_URL/api/2$1" ;;
		*=*)    echo -n "--data ${1/==/=}"  ;;
		*)      echo -n "$1"                ;;
		esac
		echo -n " "  # options separator
		shift
	done
}

_api_call() {
	curl -sSL \
		--header 'Accept: application/json' \
		--user "${PUBLIC_KEY}:${SECRET_KEY}" \
		$(_arg_parser "$@")
}

case "$1" in
	wallet|w)
		shift
		_wallet_balance "$@"
		;;
	balance|bal)
		shift
		_trading_balance "$@"
		;;
	order|o)
		shift
		_order "$@"
		;;
	history|hist)
		shift
		_history_trades "$@"
		;;
	help|-h|--help)
		cat <<-EOF
		Usage:
		  $PROGNAME endpoint [parameter ...]
		  $PROGNAME command  [parameter ...]

		  available commands:
		    [bal]ance
		    [o]rder
		    [hist]ory
			[w]allet

		  available endpoints:
		    https://api.hitbtc.com
		EOF
		;;
	*)
		_api_call "$@"
		;;
esac
