#!/usr/bin/env bash

# Feed script a url.
# If an image, it will view in feh,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

# Handle by extention
case "$1" in
	*.mkv|*.mp4|*.avi|*.mov|*.wmv|*.flv)
		coproc mpv-pip "$1" && exit 0
		;;
	*.png|*.jpg|*.jpeg|*.jpe|*.gif)
		coproc { wget -qO- "$1" | imv - ; } && exit 0
		;;
	*.mp3|*.flac|*.opus|*.mp3?source=feed)
		wget "$1" 2>/dev/null && exit 0
		;;
esac

# Handle by domain
# case "$1" in
	# http*://www.youtube.com/*|http*://youtube.com/*|http*://youtu.be/*)
	# 	coproc mpv-pip "$1" && exit 0
	# 	;;
	# http*://www.reddit.com/*|http*://redd.it/*|http*://?.redd.it/*)
		# tuir "$1" && exit 0
# esac

xdg-open "$1" &>/dev/null
