#!/bin/sh
# This script will show you the current values of the module parameters
# based on https://serverfault.com/a/389965

lsmod_parm() {
    module="$1"

    if [ ! -d "/sys/module/$module" ]; then
        echo "Module '$module' is not loaded." >&2
        return 1
    fi

    if [ ! -d "/sys/module/$module/parameters" ]; then
        echo "Parametes for '$module' is not available." >&2
        return 1
    fi

    echo "Module: $module"
    for parameter_file in "/sys/module/$module/parameters"/*; do
        printf "Parm:\t%s: " "${parameter_file##*/}"
        cat "$parameter_file"
    done
}

if [ -n "$1" ]; then
    for arg in "$@"; do
        lsmod_parm "$arg"
    done
else
    cut -f 1 -d' ' < /proc/modules | while read -r module; do
        lsmod_parm "$module"
        echo
    done
fi
