#!/bin/sh

qemu-system-x86_64 \
	-enable-kvm \
	-cpu host \
	-m 2048 \
	-netdev user,id=network0,hostfwd=tcp::8022-:22,hostfwd=tcp::8090-:80 \
	-device e1000,netdev=network0 \
	-device qemu-xhci,id=xhci \
	-device usb-tablet,bus=xhci.0 \
	-device intel-hda \
	-display sdl,show-cursor=on -vga none -device virtio-vga,xres=1200,yres=700 \
	"$@"
