# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
	# unmap some default keybindings
	{ on = "<C-c>",      run = "noop" },
	{ on = "<C-r>",      run = "noop" },
	{ on = "p",          run = "noop" },
	{ on = "P",          run = "noop" },
	{ on = "d",          run = "noop" },
	{ on = "D",          run = "noop" },
	{ on = "O",          run = "noop" },
	{ on = "x",          run = "noop" },
	{ on = "X",          run = "noop" },
	{ on = "y",          run = "noop" },
	{ on = "Y",          run = "noop" },
	{ on = "-",          run = "noop" },
	{ on = "_",          run = "noop" },
	{ on = "<C-->",      run = "noop" },
	{ on = "<C-s>",      run = "noop" },
	{ on = [ "c", "c" ], run = "noop" },
	{ on = [ "c", "p" ], run = "noop" },
	{ on = [ "c", "d" ], run = "noop" },
	{ on = [ "c", "f" ], run = "noop" },
	{ on = [ "c", "n" ], run = "noop" },
	{ on = "[",          run = "noop" },
	{ on = "]",          run = "noop" },
	{ on = "t",          run = "noop" },

	# Overwrite the default keybinding to make them ranger-like
	{ on = "q",     run = "close",              desc = "Close the current tab, or quit if it's last" },
	{ on = "Q",     run = "quit",               desc = "Quit the process" },
	{ on = "<C-q>", run = "quit --no-cwd-file", desc = "Quit without outputting cwd-file" },
	{ on = "<C-w>", run = "close",              desc = "Close the current tab, or quit if it's last" },

	# Do not jump up when moving down
	{ on = "k", run = "arrow -1", desc = "Move cursor up" },
	{ on = "j", run = "arrow 1", desc = "Move cursor down" },

	# Toggle
	{ on = "<C-v>",      run = "toggle_all",             desc = "Invert selection of all files" },
	{ on = [ "u", "v" ], run = "toggle_all --state=off", desc = "Deselect all files" },

	# Spotting
	{ on = "i", run = "spot", desc = "Spot hovered file" },

	# Operation
	{ on = "o",          run = "create",                      desc = "Create a file (ends with / for directories)" },
	{ on = "r",          run = "open --interactive",          desc = "Open selected files interactively" },
	{ on = [ "y", "y" ], run = "yank",                        desc = "Yank selected files (copy)" },
	{ on = [ "d", "d" ], run = "yank --cut",                  desc = "Yank selected files (cut)" },
	{ on = [ "p", "p" ], run = "paste",                       desc = "Paste yanked files" },
	{ on = [ "p", "o" ], run = "paste --force",               desc = "Paste yanked files (overwrite if the destination exists)" },
	{ on = [ "p", "l" ], run = "link",                        desc = "Symlink the absolute path of yanked files" },
	{ on = [ "p", "L" ], run = "link --relative",             desc = "Symlink the relative path of yanked files" },
	{ on = [ "p", "h" ], run = "hardlink",                    desc = "Hardlink yanked files" },
	{ on = [ "u", "y" ], run = "unyank",                      desc = "Cancel the yank status" },
	{ on = [ "d", "D" ], run = "remove",                      desc = "Trash selected files" },
	{ on = "<Delete>",   run = "remove",                      desc = "Trash selected files" },
	{ on = [ "d", "r" ], run = "remove --permanently",        desc = "Permanently delete selected files" },
	{ on = "a",          run = "rename --cursor=before_ext",  desc = "Rename selected file(s)" },
	{ on = "A",          run = "rename",                      desc = "Rename selected file(s)" },
	{ on = [ "c", "c" ], run = "rename --empty=stem --cursor=start", desc = "Replace filename" },
	{ on = "S",          run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
	{ on = "R",          run = "search --via=rg",             desc = "Search files by content via ripgrep" },
	{ on = "Z",          run = "plugin fzf",                  desc = "Jump to a file/directory via fzf" },
	{ on = "z",          run = "plugin zoxide",               desc = "Jump to a directory via zoxide" },

	# Copy
	{ on = [ "y", "p" ], run = "copy path",             desc = "Copy the file path" },
	{ on = [ "y", "d" ], run = "copy dirname",          desc = "Copy the directory path" },
	{ on = [ "y", "f" ], run = "copy filename",         desc = "Copy the filename" },
	{ on = [ "y", "n" ], run = "copy name_without_ext", desc = "Copy the filename without extension" },

	# Goto
	{ on = [ "g", "h" ], run = "cd ~",             desc = "Go home" },
	{ on = [ "g", "c" ], run = "cd ~/.config",     desc = "Go ~/.config" },
	{ on = [ "g", "y" ], run = "cd ~/.config/yazi", desc = "Go Yazi configuration" },
	{ on = [ "g", "d" ], run = "cd ~/Downloads",   desc = "Go ~/Downloads" },
	{ on = [ "g", "/" ], run = "cd /",             desc = "Go root" },
	{ on = [ "g", "e" ], run = "cd /etc",          desc = "Go /etc" },
	{ on = [ "g", "u" ], run = "cd /usr",          desc = "Go /usr" },
	{ on = [ "g", "v" ], run = "cd /var",          desc = "Go /var" },
	{ on = [ "g", "m" ], run = "cd /media",        desc = "Go /media" },
	{ on = [ "g", "M" ], run = "cd /mnt",          desc = "Go /mnt" },
	{ on = [ "g", "i" ], run = "cd /run/media/$USER", desc = "Go /run/media/$USER" },

	# Tabs
	{ on = "<C-n>", run = "tab_create --current", desc = "Create a new tab with CWD" },
	{ on = "<BackTab>", run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
	{ on = "<Tab>",     run = "tab_switch 1 --relative",  desc = "Switch to next tab" },

	# Launch
	{ on = "e", run = "shell --block '${EDITOR:-nvim} \"$@\"'", desc = "Open file in an editor" },
	{ on = [ "d", "u" ], run = "shell --block gdu", desc = "Run gdu in the current directory" },

	# Plugins
	{ on = "l", run = [ "plugin smart-enter", "escape --visual --select" ], desc = "Enter child directory, or open file" },
	{ on = "<Enter>", run = "plugin smart-enter", desc = "Enter child directory, or open file" },

	{ on = "F", run = "plugin smart-filter", desc = "Smart filter" },

	{ on = "<C-\\>", run = "plugin toggle-pane min-preview", desc = "Hide or show preview" },
	{ on = "<F3>", run = "plugin toggle-pane max-preview", desc = "Maximize or restore preview" },

	{ on = "<A-m>", run = "plugin mount", desc = "Show mount manager" },
	{ on = "<A-l>", run = "plugin lazygit", desc = "Run lazygit" },

	{ on = "=", run = "plugin chmod", desc = "Chmod on selected files" },
	{ on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
]

[input]

prepend_keymap = [
	{ on = "<Esc>", run = "close", desc = "Cancel input" },
]

[spot]

prepend_keymap = [
	{ on = "q", run = "close", desc = "Cancel the spot" },
]

[tasks]

prepend_keymap = [
	{ on = "q", run = "close", desc = "Close the spot" },
]

[help]

prepend_keymap = [
	{ on = "q", run = "close", desc = "Close the help" },
]
