# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"


[[manager.prepend_keymap]]
on   = "<C-\\>"
run  = "plugin toggle-pane min-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on   = "<F3>"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = "S"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = "l"
run  = [ "plugin smart-enter", "escape --visual --select" ]
desc = "Enter the child directory, or open file."

[[manager.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on  = "<A-m>"
run = "plugin mount"
desc = "Show mount manager"

[[manager.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on   = "<A-l>"
run  = "plugin lazygit"
desc = "run lazygit"

[[manager.prepend_keymap]]
on   = "="
run  = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[spot.prepend_keymap]]
on   = "q"
run  = "close"
desc = "Close the spot"

[[tasks.prepend_keymap]]
on   = "q"
run  = "close"
desc = "Cancel"

[[help.prepend_keymap]]
on   = "q"
run  = "close"
desc = "Close"
