# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
dark  = ""
light = ""

# : }}}

# : Manager {{{

[manager]
cwd = { fg = "white", bold = true }

# Hovered
hovered			= { reversed = true }
preview_hovered = { reversed = true }

# Find
find_keyword  = { fg = "yellow", italic = true }
find_position = { fg = "magenta", bg = "reset", italic = true }

# Marker
marker_copied	= { fg = "lightgreen",	bg = "lightgreen" }
marker_cut		= { fg = "lightred",	bg = "lightred" }
marker_marked	= { fg = "lightcyan",	bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Tab
tab_active	 = { reversed = true }
tab_inactive = {}
tab_width	 = 1

# Count
count_copied   = { fg = "white", bg = "green" }
count_cut	   = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "yellow" }

# Border
border_symbol = "┊"
border_style  = { fg = "black" }

# Highlighting
syntect_theme = ""

# : }}}


# : Mode {{{

[mode]

normal_main = { bg = "lightblue", fg = "black", bold = true }
normal_alt	= { fg = "lightblue", bg = "gray" }

# Select mode
select_main = { bg = "lightgreen", fg = "black", bold = true }
select_alt	= { fg = "lightgreen", bg = "gray" }

# Unset mode
unset_main = { bg = "lightmagenta", fg = "black", bold = true }
unset_alt  = { fg = "lightmagenta", bg = "gray" }

# : }}}


# : Status bar {{{

[status]
separator_open	= ""
separator_close = ""
separator_style = { fg = "black", bg = "black" }

# Progress
progress_label	= { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error	= { fg = "red", bg = "black" }

# Permissions
perm_sep   = { fg = "darkgray" }
perm_type  = { fg = "lightgreen" }
perm_read  = { fg = "lightyellow" }
perm_write = { fg = "lightred" }
perm_exec  = { fg = "lightcyan" }

# : }}}


# : Pick {{{

[pick]
border	 = { fg = "blue" }
active	 = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border	 = { fg = "blue" }
title	 = {}
value	 = {}
selected = { reversed = true }

# : }}}


# : Confirm {{{

[confirm]
border	   = { fg = "blue" }
title	   = { fg = "blue" }
content    = {}
list	   = {}
btn_yes    = { reversed = true }
btn_no	   = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : }}}


# : Completion {{{

[completion]
border	 = { fg = "blue" }
active	 = { bg = "darkgray" }
inactive = {}

# Icons
icon_file	 = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border	= { fg = "blue" }
title	= {}
hovered = { fg = "magenta", underline = true }

# : }}}


# : Which {{{

[which]
cols			= 3
mask			= { bg = "black" }
cand			= { fg = "lightcyan" }
rest			= { fg = "darkgray" }
desc			= { fg = "lightmagenta" }
separator		= "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Help {{{

[help]
on		= { fg = "magenta" }
run		= { fg = "cyan" }
desc	= { fg = "gray" }
hovered = { bg = "darkgray", bold = true }
footer	= { fg = "black", bg = "white" }

# : }}}


# : Notify {{{

[notify]
title_info	= { fg = "green" }
title_warn	= { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "yellow" },

	# Media
	{ mime = "{audio,video}/*", fg = "magenta", bold = true },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red", bold = true },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "lightyellow" },

	# Empty files
	# { mime = "inode/empty", fg = "red" },

	# Special files
	{ name = "*", is = "orphan", bg = "red", bold = true },
	{ name = "*", is = "exec"  , fg = "green", bold = true },

	# Symlinks
	{ name = "*",  fg = "cyan",   bold = true, is = "link" },
	{ name = "*/", fg = "cyan",   bold = true, is = "link" },

	# Dummy files
	{ name = "*", is = "dummy", bg = "red" },
	{ name = "*/", is = "dummy", bg = "red" },

	# Fallback
	# { name = "*", fg = "white" },
	{ name = "*/", fg = "blue", bold = true },
]


# : }}}


# : Icons {{{

[icon]

globs = []
dirs  = [
	{ name = ".config", text = "" },
	{ name = ".git", text = "" },
	{ name = "Desktop", text = "" },
	{ name = "Development", text = "" },
	{ name = "Documents", text = "" },
	{ name = "Downloads", text = "" },
	{ name = "Library", text = "" },
	{ name = "Movies", text = "" },
	{ name = "Music", text = "" },
	{ name = "Pictures", text = "" },
	{ name = "Public", text = "" },
	{ name = "Videos", text = "" },
]
files = [
	# Dotfiles
	{ name = ".DS_Store"	 , text = "" },
	{ name = ".bashprofile"  , text = "" },
	{ name = ".bashrc"		 , text = "" },
	{ name = ".gitattributes", text = "" },
	{ name = ".gitignore"	 , text = "" },
	{ name = ".gitmodules"	 , text = "" },
	{ name = ".vimrc"		 , text = "" },
	{ name = ".zprofile"	 , text = "" },
	{ name = ".zshenv"		 , text = "" },
	{ name = ".zshrc"		 , text = "" },

	# Named files
	{ name = "COPYING"		, text = "󰿃" },
	{ name = "Containerfile", text = "󰡨", fg = "#458ee6" },
	{ name = "Dockerfile"	, text = "󰡨", fg = "#458ee6" },
	{ name = "LICENSE"		, text = "", fg = "#d0bf41" },
]

ext = [
	# Programming
	{ name = "cpp"  , text = "", fg = "#519aba" },
	{ name = "css"  , text = "", fg = "#42a5f5" },
	{ name = "c"	  , text = "", fg = "#599eff" },
	{ name = "fish" , text = "" },
	{ name = "go"   , text = "", fg = "#519aba" },
	{ name = "hpp"  , text = "", fg = "#a074c4" },
	{ name = "h"	  , text = "", fg = "#a074c4" },
	{ name = "htm"  , text = "", fg = "#e44d26" },
	{ name = "html" , text = "", fg = "#e44d26" },
	{ name = "java" , text = "", fg = "#cc3e44" },
	{ name = "js"   , text = "", fg = "#F1F134" },
	{ name = "jsx"  , text = "", fg = "#20c2e3" },
	{ name = "lua"  , text = "", fg = "#51a0cf" },
	{ name = "nix"  , text = "", fg = "#7ab1db" },
	{ name = "php"  , text = "" },
	{ name = "rb"   , text = "" },
	{ name = "rs"   , text = "", fg = "#dea584" },
	{ name = "scss" , text = "" },
	{ name = "sh"   , text = "", fg = "#4d5a5e" },
	{ name = "swift", text = "" },
	{ name = "ts"   , text = "", fg = "#519aba" },
	{ name = "tsx"  , text = "" },
	{ name = "vim"  , text = "" },
	{ name = "vue"  , text = "󰡄" },
	{ name = "py"   , text = "", fg = "#ffbc03" },
	{ name = "pyc"  , text = "", fg = "#ffe291" },

	# Text
	{ name = "txt"   , text = "", fg = "#bbbbbb" },
	{ name = "csv"   , text = "", fg = "#89e051" },
	{ name = "json"  , text = "", fg = "#cbcb41" },
	{ name = "conf"  , text = "", fg = "#6d8086" }, # Configuration
	{ name = "ini"   , text = "", fg = "#6d8086" },
	{ name = "yaml"  , text = "", fg = "#6d8086" },
	{ name = "yml"   , text = "", fg = "#6d8086" },
	{ name = "toml"  , text = "", fg = "#6d8086" },
	{ name = "org"   , text = "", fg = "#77aa99" },
	{ name = "tex"   , text = "󰙩", fg = "#3d6117" }, # Plaintext typesetting
	{ name = "typ"   , text = "󰙩", fg = "#0e606a" },
	{ name = "markdown", text = "", fg = "#519aba" }, # Markdown
	{ name = "md"    , text = "", fg = "#519aba" },
	{ name = "mdx"   , text = "", fg = "#519aba" },
	{ name = "rmd"   , text = "", fg = "#519aba" },

	# Archives
	{ name = "7z"  , text = "" },
	{ name = "ace" , text = "" },
	{ name = "alz" , text = "" },
	{ name = "arc" , text = "" },
	{ name = "arj" , text = "" },
	{ name = "bz2" , text = "" },
	{ name = "bz"  , text = "" },
	{ name = "cab" , text = "" },
	{ name = "cpio", text = "" },
	{ name = "deb" , text = "" },
	{ name = "dwm" , text = "" },
	{ name = "dz"  , text = "" },
	{ name = "ear" , text = "" },
	{ name = "esd" , text = "" },
	{ name = "gz"  , text = "" },
	{ name = "jar" , text = "" },
	{ name = "lha" , text = "" },
	{ name = "lrz" , text = "" },
	{ name = "lz4" , text = "" },
	{ name = "lzh" , text = "" },
	{ name = "lzma", text = "" },
	{ name = "lzo" , text = "" },
	{ name = "lz"  , text = "" },
	{ name = "rar" , text = "" },
	{ name = "rpm" , text = "" },
	{ name = "rz"  , text = "" },
	{ name = "sar" , text = "" },
	{ name = "swm" , text = "" },
	{ name = "t7z" , text = "" },
	{ name = "tar" , text = "" },
	{ name = "taz" , text = "" },
	{ name = "tbz2", text = "" },
	{ name = "tbz" , text = "" },
	{ name = "tgz" , text = "" },
	{ name = "tlz" , text = "" },
	{ name = "txz" , text = "" },
	{ name = "tzo" , text = "" },
	{ name = "tzst", text = "" },
	{ name = "tz"  , text = "" },
	{ name = "war" , text = "" },
	{ name = "wim" , text = "" },
	{ name = "xz"  , text = "" },
	{ name = "zip" , text = "" },
	{ name = "zoo" , text = "" },
	{ name = "zst" , text = "" },
	{ name = "z"	 , text = "" },

	# Images
	{ name = "bmp"  , text = "" }, # Lossless
	{ name = "gif"  , text = "" },
	{ name = "png"  , text = "" },
	{ name = "tiff" , text = "" },
	{ name = "webp" , text = "" },
	{ name = "jpeg" , text = "" }, # Lossy
	{ name = "jpg"  , text = "" },
	{ name = "mjpeg", text = "" },
	{ name = "mjpg" , text = "" },
	{ name = "mng"  , text = "" },
	{ name = "pbm"  , text = "" },
	{ name = "pcx"  , text = "" },
	{ name = "pgm"  , text = "" },
	{ name = "ppm"  , text = "" },
	{ name = "svg"  , text = "" },
	{ name = "svgz" , text = "" },
	{ name = "tga"  , text = "" },
	{ name = "tif"  , text = "" },
	{ name = "xbm"  , text = "" },
	{ name = "xpm"  , text = "" },

	# Movies
	{ name = "asf" , text = "" },
	{ name = "avi" , text = "" },
	{ name = "cgm" , text = "" },
	{ name = "dl"  , text = "" },
	{ name = "emf" , text = "" },
	{ name = "flc" , text = "" },
	{ name = "fli" , text = "" },
	{ name = "flv" , text = "" },
	{ name = "gl"  , text = "" },
	{ name = "m2v" , text = "" },
	{ name = "m4v" , text = "" },
	{ name = "mkv" , text = "" },
	{ name = "mov" , text = "" },
	{ name = "mp4" , text = "" },
	{ name = "mp4v", text = "" },
	{ name = "mpeg", text = "" },
	{ name = "mpg" , text = "" },
	{ name = "nuv" , text = "" },
	{ name = "ogm" , text = "" },
	{ name = "ogv" , text = "" },
	{ name = "ogx" , text = "" },
	{ name = "qt"  , text = "" },
	{ name = "rm"  , text = "" },
	{ name = "rmvb", text = "" },
	{ name = "vob" , text = "" },
	{ name = "webm", text = "" },
	{ name = "wmv" , text = "" },
	{ name = "xcf" , text = "" },
	{ name = "xwd" , text = "" },
	{ name = "yuv" , text = "" },

	# Audio
	{ name = "aac" , text = "" },
	{ name = "au"  , text = "" },
	{ name = "flac", text = "" },
	{ name = "m4a" , text = "" },
	{ name = "mid" , text = "" },
	{ name = "midi", text = "" },
	{ name = "mka" , text = "" },
	{ name = "mp3" , text = "" },
	{ name = "mpc" , text = "" },
	{ name = "oga" , text = "" },
	{ name = "ogg" , text = "" },
	{ name = "opus", text = "" },
	{ name = "ra"  , text = "" },
	{ name = "spx" , text = "" },
	{ name = "wav" , text = "" },
	{ name = "xspf", text = "" },

	# Documents
	{ name = "pdf" , text = "", fg = "#b30b00" }, # Printable
	{ name = "doc" , text = "", fg = "#185abd" }, # Non plaintext docs
	{ name = "doct", text = "", fg = "#185abd" },
	{ name = "docx", text = "", fg = "#185abd" },
	{ name = "dot" , text = "", fg = "#185abd" },
	{ name = "pom" , text = "󰈩", fg = "#cb4a32" }, # Presentations
	{ name = "pot" , text = "󰈩", fg = "#cb4a32" },
	{ name = "potx", text = "󰈩", fg = "#cb4a32" },
	{ name = "ppm" , text = "󰈩", fg = "#cb4a32" },
	{ name = "ppmx", text = "󰈩", fg = "#cb4a32" },
	{ name = "pps" , text = "󰈩", fg = "#cb4a32" },
	{ name = "ppsx", text = "󰈩", fg = "#cb4a32" },
	{ name = "ppt" , text = "󰈩", fg = "#cb4a32" },
	{ name = "pptx", text = "󰈩", fg = "#cb4a32" },
	{ name = "xlc" , text = "" },
	{ name = "xlm" , text = "" },
	{ name = "xls" , text = "" },
	{ name = "xlsm", text = "" },
	{ name = "xlsx", text = "" },
	{ name = "xlt" , text = "" },
	{ name = "ods" , text = "" },
	{ name = "ots" , text = "" },
	{ name = "odg" , text = "󰽉" },

	# Lockfiles
	{ name = "lock", text = "", fg = "#bbbbbb" },

	# Misc
	{ name = "bin", text = "" },
	{ name = "exe", text = "" },
	{ name = "pkg", text = "" },
]

# : }}}
