#!/usr/bin/env bash

set -eo pipefail

profile_id="$1"
profile_name="$2"
reason="$3"
errorcode="$4"

command -v crontab >/dev/null || exit 0

dest_dir="$HOME/.local/var/backup"

case "$reason" in
	1)  # Backup process begins
		mkdir -p "$dest_dir"

		rm -f "$dest_dir/crontab"
		crontab -l > "$dest_dir/crontab"
		;;
	2)  # Backup process ends
		true
		;;
esac
